### ISSUE TITLE
Naming error

### ISSUE THREAD

**Issue by watson** [noffle/place-geo-marker#2]
According to the repo, the module is called `place-geo-marker`, but [in the package.json](https://github.com/noffle/place-geo-marker/blob/84206e81656eaa29d04c584a61ab8b987d28c615/package.json#L2) it's called `geo-place-marker` - I liker the former much more :smile:

**Comment by hackergrrl** [comment]
Hah -- fixed. I was mulling over a bunch of different names, including both of the above. Thanks for catching that.
